<?php

return [

    'quick' => ['👍', '❤️', '😂', '🎉', '😮', '😢', '🙏', '🔥'],

    'all' => [
        ['e' => '😀', 'k' => 'grinning smile happy face'],
        ['e' => '😃', 'k' => 'smile happy joy face'],
        ['e' => '😄', 'k' => 'laugh happy smile face'],
        ['e' => '😁', 'k' => 'grin smile happy face'],
        ['e' => '😆', 'k' => 'laugh haha happy face'],
        ['e' => '😅', 'k' => 'sweat laugh relief face'],
        ['e' => '🤣', 'k' => 'rofl rolling laughing floor'],
        ['e' => '😂', 'k' => 'joy tears laughing crying'],
        ['e' => '🙂', 'k' => 'slight smile face'],
        ['e' => '🙃', 'k' => 'upside down silly face'],
        ['e' => '😉', 'k' => 'wink face'],
        ['e' => '😊', 'k' => 'blush smile happy shy'],
        ['e' => '😇', 'k' => 'innocent angel halo'],
        ['e' => '🥰', 'k' => 'love hearts adore face'],
        ['e' => '😍', 'k' => 'heart eyes love face'],
        ['e' => '🤩', 'k' => 'star struck excited amazed'],
        ['e' => '😘', 'k' => 'kiss blow face'],
        ['e' => '😗', 'k' => 'kiss face'],
        ['e' => '😚', 'k' => 'kiss closed eyes'],
        ['e' => '😋', 'k' => 'yum tasty tongue delicious'],
        ['e' => '😛', 'k' => 'tongue playful face'],
        ['e' => '😜', 'k' => 'wink tongue silly'],
        ['e' => '🤪', 'k' => 'zany goofy crazy face'],
        ['e' => '😝', 'k' => 'tongue squint silly'],
        ['e' => '🤑', 'k' => 'money mouth rich'],
        ['e' => '🤗', 'k' => 'hug hands face'],
        ['e' => '🤭', 'k' => 'giggle oops hand mouth'],
        ['e' => '🤫', 'k' => 'shush quiet secret'],
        ['e' => '🤔', 'k' => 'thinking hmm consider'],
        ['e' => '🤐', 'k' => 'zip mouth silence'],
        ['e' => '🤨', 'k' => 'raised eyebrow suspicious skeptic'],
        ['e' => '😐', 'k' => 'neutral meh face'],
        ['e' => '😑', 'k' => 'expressionless blank face'],
        ['e' => '😶', 'k' => 'no mouth speechless'],
        ['e' => '😏', 'k' => 'smirk sly face'],
        ['e' => '😒', 'k' => 'unamused meh annoyed'],
        ['e' => '🙄', 'k' => 'eye roll whatever'],
        ['e' => '😬', 'k' => 'grimace awkward yikes'],
        ['e' => '🤥', 'k' => 'lying liar'],
        ['e' => '😌', 'k' => 'relieved calm content'],
        ['e' => '😔', 'k' => 'pensive sad down face'],
        ['e' => '😪', 'k' => 'sleepy tired face'],
        ['e' => '🤤', 'k' => 'drool face'],
        ['e' => '😴', 'k' => 'sleep zzz tired'],
        ['e' => '😷', 'k' => 'mask sick face'],
        ['e' => '🤒', 'k' => 'sick thermometer fever'],
        ['e' => '🤕', 'k' => 'hurt bandage injured'],
        ['e' => '🤢', 'k' => 'nausea sick gross'],
        ['e' => '🤮', 'k' => 'vomit puke sick'],
        ['e' => '🤧', 'k' => 'sneeze sick tissue'],
        ['e' => '🥵', 'k' => 'hot heat sweating'],
        ['e' => '🥶', 'k' => 'cold freezing frozen'],
        ['e' => '🥴', 'k' => 'woozy dizzy drunk'],
        ['e' => '😵', 'k' => 'dizzy knocked out'],
        ['e' => '🤯', 'k' => 'mind blown explode shock'],
        ['e' => '🤠', 'k' => 'cowboy hat face'],
        ['e' => '🥳', 'k' => 'party celebrate birthday face'],
        ['e' => '😎', 'k' => 'cool sunglasses awesome'],
        ['e' => '🤓', 'k' => 'nerd geek glasses'],
        ['e' => '🧐', 'k' => 'monocle inspect curious'],
        ['e' => '😕', 'k' => 'confused unsure face'],
        ['e' => '😟', 'k' => 'worried concern face'],
        ['e' => '🙁', 'k' => 'frown sad slight'],
        ['e' => '😮', 'k' => 'open mouth wow surprised'],
        ['e' => '😯', 'k' => 'hushed surprised'],
        ['e' => '😲', 'k' => 'astonished shocked'],
        ['e' => '😳', 'k' => 'flushed embarrassed shock'],
        ['e' => '🥺', 'k' => 'pleading puppy eyes please'],
        ['e' => '😦', 'k' => 'frown open mouth'],
        ['e' => '😨', 'k' => 'fearful scared'],
        ['e' => '😰', 'k' => 'anxious sweat nervous'],
        ['e' => '😥', 'k' => 'sad relieved disappointed'],
        ['e' => '😢', 'k' => 'cry tear sad'],
        ['e' => '😭', 'k' => 'sob crying loud sad'],
        ['e' => '😱', 'k' => 'scream shock fear'],
        ['e' => '😖', 'k' => 'confounded frustrated'],
        ['e' => '😞', 'k' => 'disappointed sad'],
        ['e' => '😓', 'k' => 'downcast sweat'],
        ['e' => '😩', 'k' => 'weary tired ugh'],
        ['e' => '😫', 'k' => 'tired exhausted ugh'],
        ['e' => '🥱', 'k' => 'yawn bored tired'],
        ['e' => '😤', 'k' => 'triumph huff proud'],
        ['e' => '😡', 'k' => 'rage angry mad'],
        ['e' => '😠', 'k' => 'angry mad'],
        ['e' => '🤬', 'k' => 'swearing curse angry'],
        ['e' => '😈', 'k' => 'devil smile mischief'],
        ['e' => '💀', 'k' => 'skull dead'],
        ['e' => '💩', 'k' => 'poop crap'],
        ['e' => '🤡', 'k' => 'clown'],
        ['e' => '👻', 'k' => 'ghost boo'],
        ['e' => '👽', 'k' => 'alien ufo'],
        ['e' => '🤖', 'k' => 'robot bot'],
        ['e' => '🎃', 'k' => 'pumpkin halloween'],
        ['e' => '😺', 'k' => 'cat smile happy'],
        ['e' => '😹', 'k' => 'cat joy laughing'],
        ['e' => '😻', 'k' => 'cat heart eyes love'],
        ['e' => '🙀', 'k' => 'cat shocked'],
        ['e' => '👋', 'k' => 'wave hi hello bye hand'],
        ['e' => '🤚', 'k' => 'raised back hand'],
        ['e' => '✋', 'k' => 'raised hand stop high five'],
        ['e' => '🖐️', 'k' => 'hand fingers splayed'],
        ['e' => '👌', 'k' => 'ok perfect hand'],
        ['e' => '🤏', 'k' => 'pinch small hand'],
        ['e' => '✌️', 'k' => 'victory peace hand'],
        ['e' => '🤞', 'k' => 'fingers crossed luck hope'],
        ['e' => '🤟', 'k' => 'love you hand sign'],
        ['e' => '🤘', 'k' => 'rock horns metal'],
        ['e' => '🤙', 'k' => 'call me shaka hand'],
        ['e' => '👈', 'k' => 'point left hand'],
        ['e' => '👉', 'k' => 'point right hand'],
        ['e' => '👆', 'k' => 'point up hand'],
        ['e' => '👇', 'k' => 'point down hand'],
        ['e' => '☝️', 'k' => 'index point up hand'],
        ['e' => '👍', 'k' => 'thumbs up yes like approve good'],
        ['e' => '👎', 'k' => 'thumbs down no dislike bad'],
        ['e' => '✊', 'k' => 'fist raised power'],
        ['e' => '👊', 'k' => 'fist bump punch'],
        ['e' => '🤛', 'k' => 'fist left bump'],
        ['e' => '🤜', 'k' => 'fist right bump'],
        ['e' => '👏', 'k' => 'clap applause bravo'],
        ['e' => '🙌', 'k' => 'raised hands praise celebrate'],
        ['e' => '👐', 'k' => 'open hands'],
        ['e' => '🤲', 'k' => 'palms up together pray'],
        ['e' => '🤝', 'k' => 'handshake deal agree'],
        ['e' => '🙏', 'k' => 'pray thanks please hands'],
        ['e' => '💪', 'k' => 'muscle strong flex'],
        ['e' => '🧠', 'k' => 'brain smart mind'],
        ['e' => '👀', 'k' => 'eyes look watch'],
        ['e' => '❤️', 'k' => 'red heart love'],
        ['e' => '🧡', 'k' => 'orange heart love'],
        ['e' => '💛', 'k' => 'yellow heart love'],
        ['e' => '💚', 'k' => 'green heart love'],
        ['e' => '💙', 'k' => 'blue heart love'],
        ['e' => '💜', 'k' => 'purple heart love'],
        ['e' => '🖤', 'k' => 'black heart'],
        ['e' => '🤍', 'k' => 'white heart'],
        ['e' => '💔', 'k' => 'broken heart sad'],
        ['e' => '💕', 'k' => 'two hearts love'],
        ['e' => '💖', 'k' => 'sparkling heart love'],
        ['e' => '💘', 'k' => 'heart arrow cupid'],
        ['e' => '💯', 'k' => 'hundred perfect score'],
        ['e' => '💢', 'k' => 'anger symbol mad'],
        ['e' => '💥', 'k' => 'boom collision explode'],
        ['e' => '💫', 'k' => 'dizzy stars'],
        ['e' => '💦', 'k' => 'sweat drops water'],
        ['e' => '💨', 'k' => 'dash wind fast'],
        ['e' => '💬', 'k' => 'speech bubble comment'],
        ['e' => '💭', 'k' => 'thought bubble'],
        ['e' => '🔥', 'k' => 'fire lit hot flame'],
        ['e' => '✨', 'k' => 'sparkles shiny magic'],
        ['e' => '🌟', 'k' => 'glowing star'],
        ['e' => '⭐', 'k' => 'star favorite'],
        ['e' => '🎉', 'k' => 'party popper celebrate tada'],
        ['e' => '🎊', 'k' => 'confetti ball celebrate'],
        ['e' => '🎈', 'k' => 'balloon party'],
        ['e' => '🎁', 'k' => 'gift present box'],
        ['e' => '🏆', 'k' => 'trophy win award'],
        ['e' => '🥇', 'k' => 'gold medal first'],
        ['e' => '🎯', 'k' => 'target bullseye direct hit'],
        ['e' => '✅', 'k' => 'check done complete yes'],
        ['e' => '❌', 'k' => 'cross no wrong'],
        ['e' => '❓', 'k' => 'question mark'],
        ['e' => '❗', 'k' => 'exclamation important'],
        ['e' => '⚠️', 'k' => 'warning caution'],
        ['e' => '☕', 'k' => 'coffee tea hot drink'],
        ['e' => '🍺', 'k' => 'beer drink cheers'],
        ['e' => '🍻', 'k' => 'beers cheers toast'],
        ['e' => '🍷', 'k' => 'wine drink'],
        ['e' => '🍕', 'k' => 'pizza food'],
        ['e' => '🍔', 'k' => 'burger food'],
        ['e' => '🍟', 'k' => 'fries food'],
        ['e' => '🌮', 'k' => 'taco food'],
        ['e' => '🍰', 'k' => 'cake dessert slice'],
        ['e' => '🎂', 'k' => 'birthday cake'],
        ['e' => '🍩', 'k' => 'donut sweet'],
        ['e' => '🍪', 'k' => 'cookie sweet'],
        ['e' => '🍫', 'k' => 'chocolate sweet'],
        ['e' => '🚀', 'k' => 'rocket launch ship fast'],
        ['e' => '💡', 'k' => 'idea lightbulb bright'],
        ['e' => '📌', 'k' => 'pin pushpin'],
        ['e' => '📎', 'k' => 'paperclip attach'],
        ['e' => '🔒', 'k' => 'lock private secure'],
        ['e' => '🔑', 'k' => 'key access'],
        ['e' => '💰', 'k' => 'money bag cash'],
        ['e' => '💸', 'k' => 'money flying spend'],
        ['e' => '📈', 'k' => 'chart up growth increase'],
        ['e' => '📉', 'k' => 'chart down decrease loss'],
        ['e' => '🐛', 'k' => 'bug insect defect'],
        ['e' => '🎵', 'k' => 'music note'],
        ['e' => '🎶', 'k' => 'music notes'],
        ['e' => '⏰', 'k' => 'alarm clock time'],
        ['e' => '📆', 'k' => 'calendar date'],
        ['e' => '🌈', 'k' => 'rainbow'],
        ['e' => '☀️', 'k' => 'sun sunny weather'],
        ['e' => '🌙', 'k' => 'moon night away'],
        ['e' => '⛅', 'k' => 'cloud sun weather'],
        ['e' => '☔', 'k' => 'umbrella rain weather'],
        ['e' => '❄️', 'k' => 'snowflake cold winter'],
        ['e' => '⚡', 'k' => 'lightning bolt zap fast'],
        ['e' => '🌊', 'k' => 'wave ocean water'],
    ],
];
